//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/MirrorDemo/Input/VRMirrorDemoInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VRMirrorDemoInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VRMirrorDemoInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VRMirrorDemoInputActions"",
    ""maps"": [
        {
            ""name"": ""VRControls"",
            ""id"": ""08b84a0c-3138-4d72-b1fe-50695797387d"",
            ""actions"": [
                {
                    ""name"": ""LGripPress"",
                    ""type"": ""Button"",
                    ""id"": ""c802a724-e367-4dfa-a870-e558602c46af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LGripAxis"",
                    ""type"": ""Value"",
                    ""id"": ""cb2f574b-a7b6-4025-9328-e3a4970499c9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RGripPress"",
                    ""type"": ""Button"",
                    ""id"": ""c7edfb1c-242c-4c86-81c6-9f50b12af9ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RGripAxis"",
                    ""type"": ""Value"",
                    ""id"": ""4d19c7b7-0892-4985-b7e6-56e49132ba09"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""XBtnTouch"",
                    ""type"": ""Button"",
                    ""id"": ""423914d2-c126-48ac-9cdc-f307c451d0fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XBtnPress"",
                    ""type"": ""Button"",
                    ""id"": ""9fa828a7-dafd-4e1b-ad4b-07e3166a28e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YBtnTouch"",
                    ""type"": ""Button"",
                    ""id"": ""2ecef673-4be4-4b91-b715-a4f8b15ed420"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YBtnPress"",
                    ""type"": ""Button"",
                    ""id"": ""3354ab48-fa05-47d6-8782-3773f062c7d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ABtnTouch"",
                    ""type"": ""Button"",
                    ""id"": ""4617e5db-c3c8-4f05-8e6d-738a281800d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ABtnPress"",
                    ""type"": ""Button"",
                    ""id"": ""752ab107-44f4-4ff3-8aaa-d49ca0084236"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BBtnTouch"",
                    ""type"": ""Button"",
                    ""id"": ""298391f2-e0fb-4a6c-8dae-eef93d947ff4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BBtnPress"",
                    ""type"": ""Button"",
                    ""id"": ""04f5b451-651f-4a97-8354-d645a9123ce7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LMenuPress"",
                    ""type"": ""Button"",
                    ""id"": ""e0a43ac9-8c8f-4150-a450-a11b78b9fd50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RMenuPress"",
                    ""type"": ""Button"",
                    ""id"": ""8d5fdf69-42d3-4ca7-bb69-c9d59d441912"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LThumbTouch"",
                    ""type"": ""Button"",
                    ""id"": ""fda59bf6-21b5-42ee-973c-2542ba757a1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LThumbPress"",
                    ""type"": ""Button"",
                    ""id"": ""d0e971ce-a624-4b84-b176-971e3018883d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RThumbTouch"",
                    ""type"": ""Button"",
                    ""id"": ""f0cc76b8-fa4c-4e21-841b-e6813bcab42b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RThumbPress"",
                    ""type"": ""Button"",
                    ""id"": ""0117a94f-b688-4f81-991d-f65e5daf5c10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTriggerTouch"",
                    ""type"": ""Button"",
                    ""id"": ""1bfed063-a627-4ff1-9fde-5e8be505d0f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTriggerPress"",
                    ""type"": ""Button"",
                    ""id"": ""027a999f-ccdd-4db3-b843-e461121618d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTriggerAxis"",
                    ""type"": ""Value"",
                    ""id"": ""0defa899-d8e3-4eba-8277-f676df29bf47"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RTriggerTouch"",
                    ""type"": ""Button"",
                    ""id"": ""715a3a61-910a-4c75-9eb7-d985e233256c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTriggerPress"",
                    ""type"": ""Button"",
                    ""id"": ""8d8fcbb5-008b-4a23-b5b5-6d6559ed62f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTriggerAxis"",
                    ""type"": ""Value"",
                    ""id"": ""a6868a64-8011-478c-9d88-eed0295beee2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LAxis2d"",
                    ""type"": ""Value"",
                    ""id"": ""4a2c02bd-4182-47d3-9093-c0271d68dd33"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RAxis2d"",
                    ""type"": ""Value"",
                    ""id"": ""02766bdd-72eb-43f0-bb75-80e6359e98b4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HMDPos"",
                    ""type"": ""Value"",
                    ""id"": ""697731ff-9881-49e6-ac9a-ad3e3e6d4093"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HMDRot"",
                    ""type"": ""Value"",
                    ""id"": ""6cccb4d7-f00e-4cb2-9ea5-9c24178ea467"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LCtrlPos"",
                    ""type"": ""Value"",
                    ""id"": ""22661031-a839-46c4-a630-d81cfe09b8b6"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RCtrlPos"",
                    ""type"": ""Value"",
                    ""id"": ""c5c03bd6-c27c-479f-8f5a-3e15602ddb44"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LCtrlRot"",
                    ""type"": ""Value"",
                    ""id"": ""e34d859c-3b8c-4edf-abed-4a80c9f44579"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RCtrlRot"",
                    ""type"": ""Value"",
                    ""id"": ""7980b424-516b-4e19-8e82-09bcc3c4de2b"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HMDCenterEyePos"",
                    ""type"": ""Value"",
                    ""id"": ""d3f341f6-3c68-4647-9744-3d49b7ba60b8"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HMDCenterEyeRot"",
                    ""type"": ""Value"",
                    ""id"": ""1856c341-39e7-4974-bfd7-7445c69d8bde"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HMDLEyePos"",
                    ""type"": ""Value"",
                    ""id"": ""b2215767-9018-47e2-9693-df50f09606c6"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HMDREyePos"",
                    ""type"": ""Value"",
                    ""id"": ""6b584dc6-88f4-457b-89af-c7f6c9acbf8e"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HMDLEyeRot"",
                    ""type"": ""Value"",
                    ""id"": ""2f03315c-bf0d-4e58-9293-70f9cd3298a7"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HMDREyeRot"",
                    ""type"": ""Value"",
                    ""id"": ""b7a2e08c-c3fa-41e5-a0d2-40a4b26e20bd"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LPointerPos"",
                    ""type"": ""Value"",
                    ""id"": ""12c7a203-233c-4005-a5a8-0213a69f3b15"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LPointerRot"",
                    ""type"": ""Value"",
                    ""id"": ""da2efdcd-e8de-4db2-bcd1-4dd604a184d3"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RPointerPos"",
                    ""type"": ""Value"",
                    ""id"": ""239f37fe-4fc6-453c-bd02-6d1a24a4ccf0"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RPointerRot"",
                    ""type"": ""Value"",
                    ""id"": ""187fdcae-45d1-47fa-af6c-a1ae51d653a7"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aa3d4e79-aed8-45cd-b282-7edb6fd6043b"",
                    ""path"": ""<OculusTouchController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LGripPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e705494-c952-42a3-82ff-9aa5cccb28b8"",
                    ""path"": ""<OculusTouchController>/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LGripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a43defa-3e90-4da3-86a9-db3e5cc6354f"",
                    ""path"": ""<OculusTouchController>{LeftHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XBtnTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a141c4ff-f07b-4e6a-bb07-2912ede8d789"",
                    ""path"": ""<OculusTouchController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XBtnPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2802d5f4-512c-45b7-ae5f-c397dec45090"",
                    ""path"": ""<OculusTouchController>{LeftHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YBtnTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""523f90e2-3c55-4acb-80ca-aa30e2fbc0d9"",
                    ""path"": ""<OculusTouchController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YBtnPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""810d7c98-fdca-4213-925f-a7a9cc19eaf3"",
                    ""path"": ""<OculusTouchController>{LeftHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LMenuPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24fcadbe-09f1-4949-91e9-500e29432802"",
                    ""path"": ""<OculusTouchController>{RightHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTriggerTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb8363b8-9a59-4600-9a26-79abec0290d2"",
                    ""path"": ""<OculusTouchController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTriggerAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79a7da0f-d10a-4c02-9768-eed557a6aee5"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LThumbTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""978df70d-678f-441e-8d0a-ea0e4989c685"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LThumbPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a26b238-5420-45a9-8445-414feec239c0"",
                    ""path"": ""<OculusTouchController>{LeftHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTriggerTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f53f5bf-cfb2-4d4e-b861-b90ee3163a74"",
                    ""path"": ""<OculusTouchController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTriggerAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5a5d9e6-0ae1-40a1-8b38-2c6faf4f7408"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAxis2d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d440ad14-1a8d-40c6-9a47-ca6728434abe"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RAxis2d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb32a6e8-29bd-4c74-aed7-47a6bf7e9dae"",
                    ""path"": ""<OculusTouchController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RGripPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81a3426d-c636-41dc-8703-809c7bcb5562"",
                    ""path"": ""<OculusTouchController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RGripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ace8f3da-a642-431b-9461-4accfb0e1b61"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ABtnTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5609bb8-bf80-4c07-91d8-a385d4eddbb5"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ABtnPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""806fb7fe-821e-4408-a824-ce0df1b050b2"",
                    ""path"": ""<OculusTouchController>{RightHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BBtnTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8b24f0f-9229-4bca-9136-3b073f9c9698"",
                    ""path"": ""<OculusTouchController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BBtnPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e54bf4e-aa2f-44ab-b7d7-a5d4906dae26"",
                    ""path"": ""<OculusTouchController>{RightHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RMenuPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49cf61eb-78c6-46a2-93ab-b5d9aca01734"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RThumbTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a7d465f-46a4-4c5d-9832-84928f500862"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RThumbPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3e8eac1-19b4-48a0-8dc8-7f8045e3df4f"",
                    ""path"": ""<OculusTouchController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTriggerPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b750c145-54cb-4524-bd51-5e679c822b08"",
                    ""path"": ""<OculusTouchController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTriggerPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bebb907f-f7ad-4023-b002-81852762aa98"",
                    ""path"": ""<XRHMD>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMDPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6173b406-e0ed-4007-8be2-7df0f6157460"",
                    ""path"": ""<OpenXRHmd>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMDRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de0766b8-597d-48b8-b49c-72d349286139"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LCtrlPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60cebb13-f637-4ab7-a315-552b721583d3"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RCtrlPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9162e9ed-c0c3-4cdd-8147-2dc164185fcc"",
                    ""path"": ""<XRController>{LeftHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LCtrlRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""197aef5a-6b53-46b4-82e4-be6871274bf3"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RCtrlRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""214ebee9-f126-46da-b1a9-2768f6bb2f7e"",
                    ""path"": ""<XRHMD>/centerEyePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMDCenterEyePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b14d588-56ea-4136-a150-fe8a8699e0a3"",
                    ""path"": ""<XRHMD>/centerEyeRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMDCenterEyeRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9780bea8-c4d8-49d3-b346-2f491e2a7886"",
                    ""path"": ""<XRHMD>/leftEyePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMDLEyePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e237da61-ce25-47d7-bb48-00d34fabb8b1"",
                    ""path"": ""<XRHMD>/rightEyePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMDREyePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0cabdf9-5f61-4ef0-bac3-5690bdb60ac9"",
                    ""path"": ""<XRHMD>/leftEyeRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMDLEyeRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0837f57c-1a0e-4f6d-a11b-a4c91762fcf0"",
                    ""path"": ""<XRHMD>/rightEyeRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HMDREyeRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a7c7eff-4b89-46af-a2b2-ea4cfefe1056"",
                    ""path"": ""<XRController>{LeftHand}/pointerPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LPointerPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1943b376-a6d6-4776-8fc3-17a16c63b0c7"",
                    ""path"": ""<XRController>{LeftHand}/pointerRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LPointerRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7cbe19d-1d78-4afd-9f6e-e431da3f095a"",
                    ""path"": ""<XRController>{RightHand}/pointerPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RPointerPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f45a62a8-02e8-4f20-980a-83cb6624249f"",
                    ""path"": ""<XRController>{RightHand}/pointerRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RPointerRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VRControls
        m_VRControls = asset.FindActionMap("VRControls", throwIfNotFound: true);
        m_VRControls_LGripPress = m_VRControls.FindAction("LGripPress", throwIfNotFound: true);
        m_VRControls_LGripAxis = m_VRControls.FindAction("LGripAxis", throwIfNotFound: true);
        m_VRControls_RGripPress = m_VRControls.FindAction("RGripPress", throwIfNotFound: true);
        m_VRControls_RGripAxis = m_VRControls.FindAction("RGripAxis", throwIfNotFound: true);
        m_VRControls_XBtnTouch = m_VRControls.FindAction("XBtnTouch", throwIfNotFound: true);
        m_VRControls_XBtnPress = m_VRControls.FindAction("XBtnPress", throwIfNotFound: true);
        m_VRControls_YBtnTouch = m_VRControls.FindAction("YBtnTouch", throwIfNotFound: true);
        m_VRControls_YBtnPress = m_VRControls.FindAction("YBtnPress", throwIfNotFound: true);
        m_VRControls_ABtnTouch = m_VRControls.FindAction("ABtnTouch", throwIfNotFound: true);
        m_VRControls_ABtnPress = m_VRControls.FindAction("ABtnPress", throwIfNotFound: true);
        m_VRControls_BBtnTouch = m_VRControls.FindAction("BBtnTouch", throwIfNotFound: true);
        m_VRControls_BBtnPress = m_VRControls.FindAction("BBtnPress", throwIfNotFound: true);
        m_VRControls_LMenuPress = m_VRControls.FindAction("LMenuPress", throwIfNotFound: true);
        m_VRControls_RMenuPress = m_VRControls.FindAction("RMenuPress", throwIfNotFound: true);
        m_VRControls_LThumbTouch = m_VRControls.FindAction("LThumbTouch", throwIfNotFound: true);
        m_VRControls_LThumbPress = m_VRControls.FindAction("LThumbPress", throwIfNotFound: true);
        m_VRControls_RThumbTouch = m_VRControls.FindAction("RThumbTouch", throwIfNotFound: true);
        m_VRControls_RThumbPress = m_VRControls.FindAction("RThumbPress", throwIfNotFound: true);
        m_VRControls_LTriggerTouch = m_VRControls.FindAction("LTriggerTouch", throwIfNotFound: true);
        m_VRControls_LTriggerPress = m_VRControls.FindAction("LTriggerPress", throwIfNotFound: true);
        m_VRControls_LTriggerAxis = m_VRControls.FindAction("LTriggerAxis", throwIfNotFound: true);
        m_VRControls_RTriggerTouch = m_VRControls.FindAction("RTriggerTouch", throwIfNotFound: true);
        m_VRControls_RTriggerPress = m_VRControls.FindAction("RTriggerPress", throwIfNotFound: true);
        m_VRControls_RTriggerAxis = m_VRControls.FindAction("RTriggerAxis", throwIfNotFound: true);
        m_VRControls_LAxis2d = m_VRControls.FindAction("LAxis2d", throwIfNotFound: true);
        m_VRControls_RAxis2d = m_VRControls.FindAction("RAxis2d", throwIfNotFound: true);
        m_VRControls_HMDPos = m_VRControls.FindAction("HMDPos", throwIfNotFound: true);
        m_VRControls_HMDRot = m_VRControls.FindAction("HMDRot", throwIfNotFound: true);
        m_VRControls_LCtrlPos = m_VRControls.FindAction("LCtrlPos", throwIfNotFound: true);
        m_VRControls_RCtrlPos = m_VRControls.FindAction("RCtrlPos", throwIfNotFound: true);
        m_VRControls_LCtrlRot = m_VRControls.FindAction("LCtrlRot", throwIfNotFound: true);
        m_VRControls_RCtrlRot = m_VRControls.FindAction("RCtrlRot", throwIfNotFound: true);
        m_VRControls_HMDCenterEyePos = m_VRControls.FindAction("HMDCenterEyePos", throwIfNotFound: true);
        m_VRControls_HMDCenterEyeRot = m_VRControls.FindAction("HMDCenterEyeRot", throwIfNotFound: true);
        m_VRControls_HMDLEyePos = m_VRControls.FindAction("HMDLEyePos", throwIfNotFound: true);
        m_VRControls_HMDREyePos = m_VRControls.FindAction("HMDREyePos", throwIfNotFound: true);
        m_VRControls_HMDLEyeRot = m_VRControls.FindAction("HMDLEyeRot", throwIfNotFound: true);
        m_VRControls_HMDREyeRot = m_VRControls.FindAction("HMDREyeRot", throwIfNotFound: true);
        m_VRControls_LPointerPos = m_VRControls.FindAction("LPointerPos", throwIfNotFound: true);
        m_VRControls_LPointerRot = m_VRControls.FindAction("LPointerRot", throwIfNotFound: true);
        m_VRControls_RPointerPos = m_VRControls.FindAction("RPointerPos", throwIfNotFound: true);
        m_VRControls_RPointerRot = m_VRControls.FindAction("RPointerRot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VRControls
    private readonly InputActionMap m_VRControls;
    private IVRControlsActions m_VRControlsActionsCallbackInterface;
    private readonly InputAction m_VRControls_LGripPress;
    private readonly InputAction m_VRControls_LGripAxis;
    private readonly InputAction m_VRControls_RGripPress;
    private readonly InputAction m_VRControls_RGripAxis;
    private readonly InputAction m_VRControls_XBtnTouch;
    private readonly InputAction m_VRControls_XBtnPress;
    private readonly InputAction m_VRControls_YBtnTouch;
    private readonly InputAction m_VRControls_YBtnPress;
    private readonly InputAction m_VRControls_ABtnTouch;
    private readonly InputAction m_VRControls_ABtnPress;
    private readonly InputAction m_VRControls_BBtnTouch;
    private readonly InputAction m_VRControls_BBtnPress;
    private readonly InputAction m_VRControls_LMenuPress;
    private readonly InputAction m_VRControls_RMenuPress;
    private readonly InputAction m_VRControls_LThumbTouch;
    private readonly InputAction m_VRControls_LThumbPress;
    private readonly InputAction m_VRControls_RThumbTouch;
    private readonly InputAction m_VRControls_RThumbPress;
    private readonly InputAction m_VRControls_LTriggerTouch;
    private readonly InputAction m_VRControls_LTriggerPress;
    private readonly InputAction m_VRControls_LTriggerAxis;
    private readonly InputAction m_VRControls_RTriggerTouch;
    private readonly InputAction m_VRControls_RTriggerPress;
    private readonly InputAction m_VRControls_RTriggerAxis;
    private readonly InputAction m_VRControls_LAxis2d;
    private readonly InputAction m_VRControls_RAxis2d;
    private readonly InputAction m_VRControls_HMDPos;
    private readonly InputAction m_VRControls_HMDRot;
    private readonly InputAction m_VRControls_LCtrlPos;
    private readonly InputAction m_VRControls_RCtrlPos;
    private readonly InputAction m_VRControls_LCtrlRot;
    private readonly InputAction m_VRControls_RCtrlRot;
    private readonly InputAction m_VRControls_HMDCenterEyePos;
    private readonly InputAction m_VRControls_HMDCenterEyeRot;
    private readonly InputAction m_VRControls_HMDLEyePos;
    private readonly InputAction m_VRControls_HMDREyePos;
    private readonly InputAction m_VRControls_HMDLEyeRot;
    private readonly InputAction m_VRControls_HMDREyeRot;
    private readonly InputAction m_VRControls_LPointerPos;
    private readonly InputAction m_VRControls_LPointerRot;
    private readonly InputAction m_VRControls_RPointerPos;
    private readonly InputAction m_VRControls_RPointerRot;
    public struct VRControlsActions
    {
        private @VRMirrorDemoInputActions m_Wrapper;
        public VRControlsActions(@VRMirrorDemoInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LGripPress => m_Wrapper.m_VRControls_LGripPress;
        public InputAction @LGripAxis => m_Wrapper.m_VRControls_LGripAxis;
        public InputAction @RGripPress => m_Wrapper.m_VRControls_RGripPress;
        public InputAction @RGripAxis => m_Wrapper.m_VRControls_RGripAxis;
        public InputAction @XBtnTouch => m_Wrapper.m_VRControls_XBtnTouch;
        public InputAction @XBtnPress => m_Wrapper.m_VRControls_XBtnPress;
        public InputAction @YBtnTouch => m_Wrapper.m_VRControls_YBtnTouch;
        public InputAction @YBtnPress => m_Wrapper.m_VRControls_YBtnPress;
        public InputAction @ABtnTouch => m_Wrapper.m_VRControls_ABtnTouch;
        public InputAction @ABtnPress => m_Wrapper.m_VRControls_ABtnPress;
        public InputAction @BBtnTouch => m_Wrapper.m_VRControls_BBtnTouch;
        public InputAction @BBtnPress => m_Wrapper.m_VRControls_BBtnPress;
        public InputAction @LMenuPress => m_Wrapper.m_VRControls_LMenuPress;
        public InputAction @RMenuPress => m_Wrapper.m_VRControls_RMenuPress;
        public InputAction @LThumbTouch => m_Wrapper.m_VRControls_LThumbTouch;
        public InputAction @LThumbPress => m_Wrapper.m_VRControls_LThumbPress;
        public InputAction @RThumbTouch => m_Wrapper.m_VRControls_RThumbTouch;
        public InputAction @RThumbPress => m_Wrapper.m_VRControls_RThumbPress;
        public InputAction @LTriggerTouch => m_Wrapper.m_VRControls_LTriggerTouch;
        public InputAction @LTriggerPress => m_Wrapper.m_VRControls_LTriggerPress;
        public InputAction @LTriggerAxis => m_Wrapper.m_VRControls_LTriggerAxis;
        public InputAction @RTriggerTouch => m_Wrapper.m_VRControls_RTriggerTouch;
        public InputAction @RTriggerPress => m_Wrapper.m_VRControls_RTriggerPress;
        public InputAction @RTriggerAxis => m_Wrapper.m_VRControls_RTriggerAxis;
        public InputAction @LAxis2d => m_Wrapper.m_VRControls_LAxis2d;
        public InputAction @RAxis2d => m_Wrapper.m_VRControls_RAxis2d;
        public InputAction @HMDPos => m_Wrapper.m_VRControls_HMDPos;
        public InputAction @HMDRot => m_Wrapper.m_VRControls_HMDRot;
        public InputAction @LCtrlPos => m_Wrapper.m_VRControls_LCtrlPos;
        public InputAction @RCtrlPos => m_Wrapper.m_VRControls_RCtrlPos;
        public InputAction @LCtrlRot => m_Wrapper.m_VRControls_LCtrlRot;
        public InputAction @RCtrlRot => m_Wrapper.m_VRControls_RCtrlRot;
        public InputAction @HMDCenterEyePos => m_Wrapper.m_VRControls_HMDCenterEyePos;
        public InputAction @HMDCenterEyeRot => m_Wrapper.m_VRControls_HMDCenterEyeRot;
        public InputAction @HMDLEyePos => m_Wrapper.m_VRControls_HMDLEyePos;
        public InputAction @HMDREyePos => m_Wrapper.m_VRControls_HMDREyePos;
        public InputAction @HMDLEyeRot => m_Wrapper.m_VRControls_HMDLEyeRot;
        public InputAction @HMDREyeRot => m_Wrapper.m_VRControls_HMDREyeRot;
        public InputAction @LPointerPos => m_Wrapper.m_VRControls_LPointerPos;
        public InputAction @LPointerRot => m_Wrapper.m_VRControls_LPointerRot;
        public InputAction @RPointerPos => m_Wrapper.m_VRControls_RPointerPos;
        public InputAction @RPointerRot => m_Wrapper.m_VRControls_RPointerRot;
        public InputActionMap Get() { return m_Wrapper.m_VRControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRControlsActions set) { return set.Get(); }
        public void SetCallbacks(IVRControlsActions instance)
        {
            if (m_Wrapper.m_VRControlsActionsCallbackInterface != null)
            {
                @LGripPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLGripPress;
                @LGripPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLGripPress;
                @LGripPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLGripPress;
                @LGripAxis.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLGripAxis;
                @LGripAxis.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLGripAxis;
                @LGripAxis.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLGripAxis;
                @RGripPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRGripPress;
                @RGripPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRGripPress;
                @RGripPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRGripPress;
                @RGripAxis.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRGripAxis;
                @RGripAxis.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRGripAxis;
                @RGripAxis.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRGripAxis;
                @XBtnTouch.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnXBtnTouch;
                @XBtnTouch.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnXBtnTouch;
                @XBtnTouch.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnXBtnTouch;
                @XBtnPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnXBtnPress;
                @XBtnPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnXBtnPress;
                @XBtnPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnXBtnPress;
                @YBtnTouch.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnYBtnTouch;
                @YBtnTouch.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnYBtnTouch;
                @YBtnTouch.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnYBtnTouch;
                @YBtnPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnYBtnPress;
                @YBtnPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnYBtnPress;
                @YBtnPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnYBtnPress;
                @ABtnTouch.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnABtnTouch;
                @ABtnTouch.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnABtnTouch;
                @ABtnTouch.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnABtnTouch;
                @ABtnPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnABtnPress;
                @ABtnPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnABtnPress;
                @ABtnPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnABtnPress;
                @BBtnTouch.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnBBtnTouch;
                @BBtnTouch.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnBBtnTouch;
                @BBtnTouch.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnBBtnTouch;
                @BBtnPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnBBtnPress;
                @BBtnPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnBBtnPress;
                @BBtnPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnBBtnPress;
                @LMenuPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLMenuPress;
                @LMenuPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLMenuPress;
                @LMenuPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLMenuPress;
                @RMenuPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRMenuPress;
                @RMenuPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRMenuPress;
                @RMenuPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRMenuPress;
                @LThumbTouch.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLThumbTouch;
                @LThumbTouch.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLThumbTouch;
                @LThumbTouch.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLThumbTouch;
                @LThumbPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLThumbPress;
                @LThumbPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLThumbPress;
                @LThumbPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLThumbPress;
                @RThumbTouch.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRThumbTouch;
                @RThumbTouch.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRThumbTouch;
                @RThumbTouch.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRThumbTouch;
                @RThumbPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRThumbPress;
                @RThumbPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRThumbPress;
                @RThumbPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRThumbPress;
                @LTriggerTouch.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerTouch;
                @LTriggerTouch.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerTouch;
                @LTriggerTouch.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerTouch;
                @LTriggerPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerPress;
                @LTriggerPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerPress;
                @LTriggerPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerPress;
                @LTriggerAxis.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerAxis;
                @LTriggerAxis.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerAxis;
                @LTriggerAxis.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLTriggerAxis;
                @RTriggerTouch.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerTouch;
                @RTriggerTouch.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerTouch;
                @RTriggerTouch.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerTouch;
                @RTriggerPress.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerPress;
                @RTriggerPress.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerPress;
                @RTriggerPress.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerPress;
                @RTriggerAxis.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerAxis;
                @RTriggerAxis.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerAxis;
                @RTriggerAxis.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRTriggerAxis;
                @LAxis2d.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLAxis2d;
                @LAxis2d.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLAxis2d;
                @LAxis2d.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLAxis2d;
                @RAxis2d.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRAxis2d;
                @RAxis2d.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRAxis2d;
                @RAxis2d.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRAxis2d;
                @HMDPos.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDPos;
                @HMDPos.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDPos;
                @HMDPos.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDPos;
                @HMDRot.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDRot;
                @HMDRot.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDRot;
                @HMDRot.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDRot;
                @LCtrlPos.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLCtrlPos;
                @LCtrlPos.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLCtrlPos;
                @LCtrlPos.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLCtrlPos;
                @RCtrlPos.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRCtrlPos;
                @RCtrlPos.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRCtrlPos;
                @RCtrlPos.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRCtrlPos;
                @LCtrlRot.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLCtrlRot;
                @LCtrlRot.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLCtrlRot;
                @LCtrlRot.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLCtrlRot;
                @RCtrlRot.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRCtrlRot;
                @RCtrlRot.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRCtrlRot;
                @RCtrlRot.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRCtrlRot;
                @HMDCenterEyePos.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDCenterEyePos;
                @HMDCenterEyePos.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDCenterEyePos;
                @HMDCenterEyePos.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDCenterEyePos;
                @HMDCenterEyeRot.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDCenterEyeRot;
                @HMDCenterEyeRot.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDCenterEyeRot;
                @HMDCenterEyeRot.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDCenterEyeRot;
                @HMDLEyePos.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDLEyePos;
                @HMDLEyePos.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDLEyePos;
                @HMDLEyePos.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDLEyePos;
                @HMDREyePos.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDREyePos;
                @HMDREyePos.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDREyePos;
                @HMDREyePos.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDREyePos;
                @HMDLEyeRot.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDLEyeRot;
                @HMDLEyeRot.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDLEyeRot;
                @HMDLEyeRot.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDLEyeRot;
                @HMDREyeRot.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDREyeRot;
                @HMDREyeRot.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDREyeRot;
                @HMDREyeRot.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnHMDREyeRot;
                @LPointerPos.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLPointerPos;
                @LPointerPos.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLPointerPos;
                @LPointerPos.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLPointerPos;
                @LPointerRot.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLPointerRot;
                @LPointerRot.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLPointerRot;
                @LPointerRot.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnLPointerRot;
                @RPointerPos.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRPointerPos;
                @RPointerPos.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRPointerPos;
                @RPointerPos.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRPointerPos;
                @RPointerRot.started -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRPointerRot;
                @RPointerRot.performed -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRPointerRot;
                @RPointerRot.canceled -= m_Wrapper.m_VRControlsActionsCallbackInterface.OnRPointerRot;
            }
            m_Wrapper.m_VRControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LGripPress.started += instance.OnLGripPress;
                @LGripPress.performed += instance.OnLGripPress;
                @LGripPress.canceled += instance.OnLGripPress;
                @LGripAxis.started += instance.OnLGripAxis;
                @LGripAxis.performed += instance.OnLGripAxis;
                @LGripAxis.canceled += instance.OnLGripAxis;
                @RGripPress.started += instance.OnRGripPress;
                @RGripPress.performed += instance.OnRGripPress;
                @RGripPress.canceled += instance.OnRGripPress;
                @RGripAxis.started += instance.OnRGripAxis;
                @RGripAxis.performed += instance.OnRGripAxis;
                @RGripAxis.canceled += instance.OnRGripAxis;
                @XBtnTouch.started += instance.OnXBtnTouch;
                @XBtnTouch.performed += instance.OnXBtnTouch;
                @XBtnTouch.canceled += instance.OnXBtnTouch;
                @XBtnPress.started += instance.OnXBtnPress;
                @XBtnPress.performed += instance.OnXBtnPress;
                @XBtnPress.canceled += instance.OnXBtnPress;
                @YBtnTouch.started += instance.OnYBtnTouch;
                @YBtnTouch.performed += instance.OnYBtnTouch;
                @YBtnTouch.canceled += instance.OnYBtnTouch;
                @YBtnPress.started += instance.OnYBtnPress;
                @YBtnPress.performed += instance.OnYBtnPress;
                @YBtnPress.canceled += instance.OnYBtnPress;
                @ABtnTouch.started += instance.OnABtnTouch;
                @ABtnTouch.performed += instance.OnABtnTouch;
                @ABtnTouch.canceled += instance.OnABtnTouch;
                @ABtnPress.started += instance.OnABtnPress;
                @ABtnPress.performed += instance.OnABtnPress;
                @ABtnPress.canceled += instance.OnABtnPress;
                @BBtnTouch.started += instance.OnBBtnTouch;
                @BBtnTouch.performed += instance.OnBBtnTouch;
                @BBtnTouch.canceled += instance.OnBBtnTouch;
                @BBtnPress.started += instance.OnBBtnPress;
                @BBtnPress.performed += instance.OnBBtnPress;
                @BBtnPress.canceled += instance.OnBBtnPress;
                @LMenuPress.started += instance.OnLMenuPress;
                @LMenuPress.performed += instance.OnLMenuPress;
                @LMenuPress.canceled += instance.OnLMenuPress;
                @RMenuPress.started += instance.OnRMenuPress;
                @RMenuPress.performed += instance.OnRMenuPress;
                @RMenuPress.canceled += instance.OnRMenuPress;
                @LThumbTouch.started += instance.OnLThumbTouch;
                @LThumbTouch.performed += instance.OnLThumbTouch;
                @LThumbTouch.canceled += instance.OnLThumbTouch;
                @LThumbPress.started += instance.OnLThumbPress;
                @LThumbPress.performed += instance.OnLThumbPress;
                @LThumbPress.canceled += instance.OnLThumbPress;
                @RThumbTouch.started += instance.OnRThumbTouch;
                @RThumbTouch.performed += instance.OnRThumbTouch;
                @RThumbTouch.canceled += instance.OnRThumbTouch;
                @RThumbPress.started += instance.OnRThumbPress;
                @RThumbPress.performed += instance.OnRThumbPress;
                @RThumbPress.canceled += instance.OnRThumbPress;
                @LTriggerTouch.started += instance.OnLTriggerTouch;
                @LTriggerTouch.performed += instance.OnLTriggerTouch;
                @LTriggerTouch.canceled += instance.OnLTriggerTouch;
                @LTriggerPress.started += instance.OnLTriggerPress;
                @LTriggerPress.performed += instance.OnLTriggerPress;
                @LTriggerPress.canceled += instance.OnLTriggerPress;
                @LTriggerAxis.started += instance.OnLTriggerAxis;
                @LTriggerAxis.performed += instance.OnLTriggerAxis;
                @LTriggerAxis.canceled += instance.OnLTriggerAxis;
                @RTriggerTouch.started += instance.OnRTriggerTouch;
                @RTriggerTouch.performed += instance.OnRTriggerTouch;
                @RTriggerTouch.canceled += instance.OnRTriggerTouch;
                @RTriggerPress.started += instance.OnRTriggerPress;
                @RTriggerPress.performed += instance.OnRTriggerPress;
                @RTriggerPress.canceled += instance.OnRTriggerPress;
                @RTriggerAxis.started += instance.OnRTriggerAxis;
                @RTriggerAxis.performed += instance.OnRTriggerAxis;
                @RTriggerAxis.canceled += instance.OnRTriggerAxis;
                @LAxis2d.started += instance.OnLAxis2d;
                @LAxis2d.performed += instance.OnLAxis2d;
                @LAxis2d.canceled += instance.OnLAxis2d;
                @RAxis2d.started += instance.OnRAxis2d;
                @RAxis2d.performed += instance.OnRAxis2d;
                @RAxis2d.canceled += instance.OnRAxis2d;
                @HMDPos.started += instance.OnHMDPos;
                @HMDPos.performed += instance.OnHMDPos;
                @HMDPos.canceled += instance.OnHMDPos;
                @HMDRot.started += instance.OnHMDRot;
                @HMDRot.performed += instance.OnHMDRot;
                @HMDRot.canceled += instance.OnHMDRot;
                @LCtrlPos.started += instance.OnLCtrlPos;
                @LCtrlPos.performed += instance.OnLCtrlPos;
                @LCtrlPos.canceled += instance.OnLCtrlPos;
                @RCtrlPos.started += instance.OnRCtrlPos;
                @RCtrlPos.performed += instance.OnRCtrlPos;
                @RCtrlPos.canceled += instance.OnRCtrlPos;
                @LCtrlRot.started += instance.OnLCtrlRot;
                @LCtrlRot.performed += instance.OnLCtrlRot;
                @LCtrlRot.canceled += instance.OnLCtrlRot;
                @RCtrlRot.started += instance.OnRCtrlRot;
                @RCtrlRot.performed += instance.OnRCtrlRot;
                @RCtrlRot.canceled += instance.OnRCtrlRot;
                @HMDCenterEyePos.started += instance.OnHMDCenterEyePos;
                @HMDCenterEyePos.performed += instance.OnHMDCenterEyePos;
                @HMDCenterEyePos.canceled += instance.OnHMDCenterEyePos;
                @HMDCenterEyeRot.started += instance.OnHMDCenterEyeRot;
                @HMDCenterEyeRot.performed += instance.OnHMDCenterEyeRot;
                @HMDCenterEyeRot.canceled += instance.OnHMDCenterEyeRot;
                @HMDLEyePos.started += instance.OnHMDLEyePos;
                @HMDLEyePos.performed += instance.OnHMDLEyePos;
                @HMDLEyePos.canceled += instance.OnHMDLEyePos;
                @HMDREyePos.started += instance.OnHMDREyePos;
                @HMDREyePos.performed += instance.OnHMDREyePos;
                @HMDREyePos.canceled += instance.OnHMDREyePos;
                @HMDLEyeRot.started += instance.OnHMDLEyeRot;
                @HMDLEyeRot.performed += instance.OnHMDLEyeRot;
                @HMDLEyeRot.canceled += instance.OnHMDLEyeRot;
                @HMDREyeRot.started += instance.OnHMDREyeRot;
                @HMDREyeRot.performed += instance.OnHMDREyeRot;
                @HMDREyeRot.canceled += instance.OnHMDREyeRot;
                @LPointerPos.started += instance.OnLPointerPos;
                @LPointerPos.performed += instance.OnLPointerPos;
                @LPointerPos.canceled += instance.OnLPointerPos;
                @LPointerRot.started += instance.OnLPointerRot;
                @LPointerRot.performed += instance.OnLPointerRot;
                @LPointerRot.canceled += instance.OnLPointerRot;
                @RPointerPos.started += instance.OnRPointerPos;
                @RPointerPos.performed += instance.OnRPointerPos;
                @RPointerPos.canceled += instance.OnRPointerPos;
                @RPointerRot.started += instance.OnRPointerRot;
                @RPointerRot.performed += instance.OnRPointerRot;
                @RPointerRot.canceled += instance.OnRPointerRot;
            }
        }
    }
    public VRControlsActions @VRControls => new VRControlsActions(this);
    public interface IVRControlsActions
    {
        void OnLGripPress(InputAction.CallbackContext context);
        void OnLGripAxis(InputAction.CallbackContext context);
        void OnRGripPress(InputAction.CallbackContext context);
        void OnRGripAxis(InputAction.CallbackContext context);
        void OnXBtnTouch(InputAction.CallbackContext context);
        void OnXBtnPress(InputAction.CallbackContext context);
        void OnYBtnTouch(InputAction.CallbackContext context);
        void OnYBtnPress(InputAction.CallbackContext context);
        void OnABtnTouch(InputAction.CallbackContext context);
        void OnABtnPress(InputAction.CallbackContext context);
        void OnBBtnTouch(InputAction.CallbackContext context);
        void OnBBtnPress(InputAction.CallbackContext context);
        void OnLMenuPress(InputAction.CallbackContext context);
        void OnRMenuPress(InputAction.CallbackContext context);
        void OnLThumbTouch(InputAction.CallbackContext context);
        void OnLThumbPress(InputAction.CallbackContext context);
        void OnRThumbTouch(InputAction.CallbackContext context);
        void OnRThumbPress(InputAction.CallbackContext context);
        void OnLTriggerTouch(InputAction.CallbackContext context);
        void OnLTriggerPress(InputAction.CallbackContext context);
        void OnLTriggerAxis(InputAction.CallbackContext context);
        void OnRTriggerTouch(InputAction.CallbackContext context);
        void OnRTriggerPress(InputAction.CallbackContext context);
        void OnRTriggerAxis(InputAction.CallbackContext context);
        void OnLAxis2d(InputAction.CallbackContext context);
        void OnRAxis2d(InputAction.CallbackContext context);
        void OnHMDPos(InputAction.CallbackContext context);
        void OnHMDRot(InputAction.CallbackContext context);
        void OnLCtrlPos(InputAction.CallbackContext context);
        void OnRCtrlPos(InputAction.CallbackContext context);
        void OnLCtrlRot(InputAction.CallbackContext context);
        void OnRCtrlRot(InputAction.CallbackContext context);
        void OnHMDCenterEyePos(InputAction.CallbackContext context);
        void OnHMDCenterEyeRot(InputAction.CallbackContext context);
        void OnHMDLEyePos(InputAction.CallbackContext context);
        void OnHMDREyePos(InputAction.CallbackContext context);
        void OnHMDLEyeRot(InputAction.CallbackContext context);
        void OnHMDREyeRot(InputAction.CallbackContext context);
        void OnLPointerPos(InputAction.CallbackContext context);
        void OnLPointerRot(InputAction.CallbackContext context);
        void OnRPointerPos(InputAction.CallbackContext context);
        void OnRPointerRot(InputAction.CallbackContext context);
    }
}
